// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjtzat8Q0si4BHRx8zbdSKsLX_rb6upAs',
    appId: '1:320206510852:web:8635ffe2e299a6cf2c4e51',
    messagingSenderId: '320206510852',
    projectId: 'knowyemployeee',
    authDomain: 'knowyemployeee.firebaseapp.com',
    storageBucket: 'knowyemployeee.appspot.com',
    measurementId: 'G-RZM8FNGJ61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU-RWeBuAg8v2fI7bZ3CfExJDyhwlN9-I',
    appId: '1:320206510852:android:d71c7b4443e40ef02c4e51',
    messagingSenderId: '320206510852',
    projectId: 'knowyemployeee',
    storageBucket: 'knowyemployeee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzDCkUIX8cc0sIcggM94f5ITlNPJK2LpM',
    appId: '1:320206510852:ios:28276c5679fb01842c4e51',
    messagingSenderId: '320206510852',
    projectId: 'knowyemployeee',
    storageBucket: 'knowyemployeee.appspot.com',
    iosClientId: '320206510852-33qf2ll4e7u6gso197nlm4iiisbfl731.apps.googleusercontent.com',
    iosBundleId: 'com.github.santhoshjke.kye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzDCkUIX8cc0sIcggM94f5ITlNPJK2LpM',
    appId: '1:320206510852:ios:28276c5679fb01842c4e51',
    messagingSenderId: '320206510852',
    projectId: 'knowyemployeee',
    storageBucket: 'knowyemployeee.appspot.com',
    iosClientId: '320206510852-33qf2ll4e7u6gso197nlm4iiisbfl731.apps.googleusercontent.com',
    iosBundleId: 'com.github.santhoshjke.kye',
  );
}
